---
title: The ultimate Super Netball Fantasy team 2021
author: Afableco
date: '2021-10-28'
slug: the-ultimate-super-netball-fantasy-team-2021
draft: true
categories: []
tags:
  - Super-Netball
  - Giants-Netball
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-28T21:15:00+11:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

This year was the first time I have ever tried my hand in a fantasy sports competition, [2021 FANTASY NETBALL – SSN](https://netballscoop.com/forums/topic/2021-fantasy-netball-ssn/). My eldest daughter was keen, so I thought it would be a bit of fun. I must admit  I didn't really give it a lot of thought beforehand. Just as the season was about to commence, I picked a team that I thought looked good - it was slightly Giants heavy - and the season was under way. Round 1 and Keira Austin goes down with a ruptured ACL. My season did not look up from there, and to add salt to the wound my daugter was beating me consistantly each week. My interest dwindled.

So, I want to get a bit of a hang on how to pick a good team and start next year prepared and engaged. In this post, I want to look at which team would have been the ultimate starting fantasy netball team. I would look at the ultimate team with weekly trades, up to the limit, but I am sure the computational load of doing that would be enormous. I would have to find some heuristic.

## Rules of fantasy netball


## Thanks

